### ISSUE TITLE
Caching problems when using uploads folder

### ISSUE THREAD

**Issue by greatestview** [palasthotel/ph-wp-aggregator#3]
Hey @EdwardBock,

We experienced an ugly bug today on a customer site: The aggregated javascript files were delivered broken. Example:

![bildschirmfoto 2016-09-12 um 19 06 35](https://cloud.githubusercontent.com/assets/2060276/18445278/1b73357c-791d-11e6-8b00-caad5b967468.png)

I think it is caused by Varnish trying to cache the JS file, while it is still being build. When bypassing Varnish, the files look okay. As a quick solution we switched back to deploying the aggregated files via theme folder.

Do you have a solution for this?

**Comment by EdwardBock** [comment]
There is a purge request after building the file now. Hope this problem is none anymore.

Commit:

9a5506459853f781487f18327fdcdf1754e06295

**Comment by greatestview** [comment]
Sounds good :+1:
