### ISSUE TITLE
Remove comments

### ISSUE THREAD

**Issue by greatestview** [palasthotel/ph-wp-aggregator#5]
Contrary to minifying (#1) removing comments would have a noticeable impact on the file size.

**Comment by EdwardBock** [comment]
@greatestview 

You can use a filter to specify what scripts should not be included:

https://github.com/palasthotel/ph-wp-aggregator/blob/master/ph-aggregator.php#L375

**Comment by greatestview** [comment]
@EdwardBock, I think that’s an answer to issue #6? :)

**Comment by EdwardBock** [comment]
@greatestview 

With Version 2.0 comments script is only aggreated on pages that need comments. Please check

**Comment by greatestview** [comment]
:+1:
