### ISSUE TITLE
Conflict with external scripts

### ISSUE THREAD

**Issue by greatestview** [palasthotel/ph-wp-aggregator#6]
When I try this in *functions.php* inside *wp_enqueue_scripts* hook:

```
wp_enqueue_script(
	'jquery',
	'https://code.jquery.com/jquery-2.1.4.min.js'
);

// …

wp_enqueue_script(
	'some-other-script',
	get_template_directory_uri() . '/some-other-script.js',
	array( 'jquery' )
);
```

Expected: jquery-2.1.4.min.js is included via https://code.jquery.com/
Actual behaviour: jquery-2.1.4.min.js is not loaded anywhere.

**Comment by EdwardBock** [comment]
@greatestview 

Also working with 2.0 now. Please check.

**Comment by greatestview** [comment]
N1c3!
