### ISSUE TITLE
localized scripts

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/ph-wp-aggregator#7]
There are problems when locaizing scripts ( @greatestview told me)

**Comment by greatestview** [comment]
Yes, when you aggregate on localhost and deploy those aggregated scripts to the server, they still have localhost in them. maybe you could stripp out the server part of the urls? So that http://localhost/path will become /path?

**Comment by EdwardBock** [comment]
@greatestview 

That is fixed with update 2.0

**Comment by EdwardBock** [comment]
Ahm, no please check and than you close it ;)

**Comment by greatestview** [comment]
W0rx!
