### ISSUE TITLE
Prevent following JavaScript from executing after error

### ISSUE THREAD

**Issue by greatestview** [palasthotel/ph-wp-aggregator#8]
JavaScript naturally stops the execution of a script for 1) the whole JS-file and 2) the whole script tag. That means, that JS does not harm following scripts, if they are placed in separate files or in seperate script tags.

If we aggregate scripts into one file, one error at the top will prevent all other following scripts from execution, regardless of function wrappers or similar.

The only way to prevent this, is to use try and catch blocks. That is what we want to build into this aggregator, [somewhere around here](https://github.com/palasthotel/ph-wp-aggregator/blob/master/ph-aggregator.php#L320-L337). Code example: http://codepen.io/greatestview/pen/QpqyZy

**Comment by greatestview** [comment]
@EdwardBock, I’ve implemented that right now ([commit](https://github.com/palasthotel/ph-wp-aggregator/commit/c615886df79804ce36adcd569a855e1b20f3b1c2)). Could you upload the new update to WordPress.org?

**Comment by EdwardBock** [comment]
GREAT. Thanks!
